#!/usr/bin/env python

from math import sin, cos
import rospy

from geometry_msgs.msg import Quaternion, Twist
from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry
from sensor_msgs.msg import Range
from tf.broadcaster import TransformBroadcaster

import ranger

RATE = 10 #Hz
ODOM_FRAME = "odom"
BASE_FRAME = "base_link"


rospy.init_node('ranger_ros')
r = rospy.Rate(RATE)
odomPub = rospy.Publisher("odom", Odometry, queue_size=1)
odomBroadcaster = TransformBroadcaster()

irPub = [rospy.Publisher("ir_left", Range, queue_size=1),
         rospy.Publisher("ir_center", Range, queue_size=1),
         rospy.Publisher("ir_right", Range, queue_size=1)]

range_left = Range()
range_left.header.frame_id = "ir_left"
range_left.radiation_type = Range.INFRARED
range_left.field_of_view = 0.2 # ~10deg
range_left.min_range = 0.025 # according to my measurments
range_left.max_range = 0.30 # according to my measurments

range_center = Range()
range_center.header.frame_id = "ir_center"
range_center.radiation_type = Range.INFRARED
range_center.field_of_view = 0.2 # ~10 deg
range_center.min_range = 0.35 # according to my measurments
range_center.max_range = 2.0 # according to my measurments

range_right = Range()
range_right.header.frame_id = "ir_right"
range_right.radiation_type = Range.INFRARED
range_right.field_of_view = 0.2 # ~10deg
range_right.min_range = 0.025 # according to my measurments
range_right.max_range = 0.30 # according to my measurments



with ranger.Ranger() as robot:

    rospy.loginfo("ROS Ranger interface started. Starting to broadcast odometry and TF transform of base_link")

    def command_cb(msg):
        robot.speed(v = msg.linear.x, w = msg.angular.z)

    cmd_vel = rospy.Subscriber("cmd_vel", Twist, command_cb)

    state = robot.state

    while not rospy.is_shutdown():
        now = rospy.Time.now()

        # we get all the state once to ensure (as much as possible) temporal
        # consistency
        x, y, theta = state.x, state.y, state.theta
        v, w = state.v, state.w
        ir_left, ir_center, ir_right = state.ir_left, state.ir_center, state.ir_right

        # TF base_link
        quaternion = Quaternion()
        quaternion.x = 0.0
        quaternion.y = 0.0
        quaternion.z = sin( theta / 2 )
        quaternion.w = cos( theta / 2 )
        odomBroadcaster.sendTransform(
            (x, y, 0),
            (quaternion.x, quaternion.y, quaternion.z, quaternion.w),
            now,
            BASE_FRAME,
            ODOM_FRAME
            )

        # ODOMETRY
        odom = Odometry()
        odom.header.stamp = now
        odom.header.frame_id = ODOM_FRAME
        odom.pose.pose.position.x = x
        odom.pose.pose.position.y = y
        odom.pose.pose.position.z = 0
        odom.pose.pose.orientation = quaternion
        odom.child_frame_id = BASE_FRAME
        odom.twist.twist.linear.x = v
        odom.twist.twist.linear.y = 0
        odom.twist.twist.angular.z = w

        odomPub.publish(odom)

        # IR SENSORS
        range_left.range = ir_left
        range_center.range = ir_center
        range_right.range = ir_right
        irPub[0].publish(range_left)
        irPub[1].publish(range_center)
        irPub[2].publish(range_right)



        # DONE!
        r.sleep()
