#!/usr/bin/env python
import time
import roslib;roslib.load_manifest('ranger_ros')
from ranger_ros.ranger import Ranger

import rospy

def ranger_server():
    rospy.init_node('ranger_server')
    ranger = Ranger()
    rospy.loginfo("ROS Ranger interface started")

    while not rospy.is_shutdown():
        time.sleep(0.05)
        ranger.heartbeat()

if __name__ == "__main__":
    ranger_server()
