#!/usr/bin/env python

import roslib;roslib.load_manifest('ranger_ros')
from ranger_ros.ranger import Ranger

import rospy

def ranger_server():
    rospy.init_node('ranger_server')
    ranger = Ranger()
    rospy.loginfo("ROS Ranger interface started")
    rospy.spin()

if __name__ == "__main__":
    ranger_server()
