#!/usr/bin/env python

import time
import pygame
import sys
from geometry_msgs.msg import Twist
import rospy

MAX_LINEAR_SPEED = 0.2 # m/s
MAX_ANGULAR_SPEED = 0.4 # rad/s

rospy.init_node('ranger_vw_ctrl')
twist = rospy.Publisher('/cmd_vel', Twist)

v = 0.0
w = 0.0

msg = Twist()

pygame.init()

done = False

clock = pygame.time.Clock()

pygame.joystick.init()
joystick_count = pygame.joystick.get_count()

if joystick_count == 0:
    rospy.logerr("Plug your joystick!")
    sys.exit(1)

joystick = pygame.joystick.Joystick(0)
joystick.init()

v_prev = 0.0
w_prev = 0.0

while not rospy.is_shutdown() and done==False:
    for event in pygame.event.get(): # User did something
        if event.type == pygame.JOYBUTTONDOWN:
            print("Leaving now")
            done = True

    w = -joystick.get_axis( 0 ) * MAX_ANGULAR_SPEED
    v = -joystick.get_axis( 1 ) * MAX_LINEAR_SPEED

    # Limit to 20 frames per second
    clock.tick(20)

    if w != w_prev or v != v_prev:
        rospy.logdebug("V:%s      W:%s" % (v,w))

        msg.linear.x = v
        msg.angular.z = w
        twist.publish(msg)
        v_prev = v
        w_prev = w

msg.linear.x = 0.
msg.angular.z = 0.
twist.publish(msg)
time.sleep(0.5)
pygame.quit ()

